language: python
python:
  - "3.4"
#before_install:
#  - sudo apt-get update
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 --ignore=E402,E501 generate.py
  - python generate.py -p cv.yaml
